site_name: Samuel Cavalcanti

nav:
 - Sobre mim: index.md
 - Bacharel em ciência e tecnologia: c&t.md
 - Bacharel em engenharia da computação: undergraduate_computer_engineering.md

theme:
  name: material

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  language: pt-BR
  
 

  features:
          - navigation.indexes
          - header.autohide